#include "register.c"

enum {
    TRAP_GETC = 0x20,//READ CHARACTER
    TRAP_OUT = 0X21,//OUTPUT TO CONSOLE
    TRAP_PUTS = 0X22,//WRITE STRING TO CONSOLE
    TRAP_IN = 0X23,//PRINT PROMPT TO CONSOLE 
    TRAP_PUTSP =0X24,//WRITE A STRING OF ASCII CHARACTER 
    TRAP_HALT = 0X25//HALT PROGRAM
};

